# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, configurator, dlist, filepath, glpkHs, graphviz
, labeledTree, lens, mtl, parsek, polynomialsBernstein, text
, typographyGeometry, vector
}:

cabal.mkDerivation (self: {
  pname = "marxup";
  version = "3.0.0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    configurator dlist filepath glpkHs graphviz labeledTree lens mtl
    parsek polynomialsBernstein text typographyGeometry vector
  ];
  meta = {
    description = "Markup language preprocessor for Haskell";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
